### ISSUE TITLE
run --python doesn't seem to work

### ISSUE THREAD

**Issue by brettcannon** [python/performance#12]
I tried running the benchmark with `python3 -m performance run --python ../cpython/3.6/python.exe --rigorous -b all -o ../3.6-perf.json`, but `3.6-perf.json` says `"python_version":"3.5.2 (64-bit)"`, but running `../cpython/3.6/python.exe` says it's `3.6.0b1+`.

**Comment by haypo** [comment]
What is your platform? Mac OS X or Windows?

You can debug using the venv command:

```
$ python3 -m performance venv create --python=python2
(...)
The virtual environment venv/cpython2.7-a845ea3b7d3d has been created

$ venv/cpython2.7-a845ea3b7d3d/bin/python --version
Python 2.7.12
```

**Comment by haypo** [comment]
You may also try to avoid completly the usage of a virtual environment using the internal --inside-venv command line option. But you must install performance/requirements.txt using pip:

```
python -m pip install -r performance/requirements.txt
python -m performance run (...) --inside-venv
```

Note: I didn't try :-)

**Comment by haypo** [comment]
The issue doesn't seem to be fixed, why closing it? What is your OS?

**Comment by haypo** [comment]
I tried this command on Windows:

```
\Python35\Python -m performance run -b call_simple -o json --fast --python=\Python27\python.exe
```

Thanks to the issue #11, I directly got the confirmation: the benchmark was run on Python 2. By the way, it created a virtual environment called venv\cpython-27-(...)\.

So at least on Windows with the development version, run --python works ;-)

**Comment by brettcannon** [comment]
I closed it because I thought you suggested it was just on my end and being sick and such was leading me to not taking the time to valid, so instead of letting this just sit here I figured it was better just to close.

**Comment by haypo** [comment]
I also tested performance on Mac OS X: performance 0.2.3 (master branch) works well ;-)
