### ISSUE TITLE
Add the regex-dna benchmark

### ISSUE THREAD

**Issue by haypo** [python/performance#15]
See http://bugs.python.org/issue26436

**Comment by matrixise** [comment]
See http://bugs.python.org/issue26436 for details.

Proposed patch adds the regex-dna benchmark from The Computer Language Benchmarks Game (http://benchmarksgame.alioth.debian.org/). This is artificial but well known benchmark.

The patch is based on regex-dna Python 3 #5 program and fasta Python 3 #3 program (for generating input).

http://bugs.python.org/file42028/bm_regex_dna.patch

I have closed http://bugs.python.org/issue26436

**Comment by haypo** [comment]
I created the pull request #17 with Serhiy's patch (updated for latest perf and performance).

**Comment by haypo** [comment]
Good news: performance 0.3.1 includes the new benchmarks. FYI it's called "fasta" in pyston benchmark suite.
