### ISSUE TITLE
Semantic Difference Between Python 2 and Python 3

### ISSUE THREAD

**Issue by egalli** [python/performance#21]
While looking for performance differences between CPython 2.7 and CPython 3.6, I noticed the same benchmark would exercise different parts of the interpreter.

**pybench/Calls.py** (PythonMethodCalls), **pybench/Lookups.py** (SpecialClassAttribute, NormalClassAttribute, SpecialInstanceAttribute, and NormalInstanceAttribute):

These benchmarks are using the syntax `class c:` to create classes. This syntax creates old-styles classes in Python 2 and new-style classes in Python 3. Should we create separate tests for old-style classes (disabled in Python 3) and new-style classes?

**pybench/Strings.py**:

Due to the `str` changes in Python 3, it is hard to use these benchmarks to compare between Python 2 and Python 3. While we could use `bytes` in Python 3 (similar to how `unicode` is being used Unicode.py), not use if that is the correct approach. Because, at that point, it would more of an ascii string benchmark rather than a `str`.

Thanks!

**Comment by haypo** [comment]
I modified pybench to be able to run it on Python 2 and Python 3, but I agree that the code doesn't do exactly the same thing between the two versions.

I'm not a big fan of pybench. First, results look very unstable, so I decided to exclude it from the default group of performance. They are really tiny microbenchmarks, so heavily impacted by all tiny things like CPU caches and code location.

I prefer to use more "macro" benchmarks.

But ok, well, about pybench: what do you suggest?

**Comment by haypo** [comment]
I removed the pybench from performance. I moved it to my other https://github.com/haypo/pymicrobench project. So I close this PR now.
