### ISSUE TITLE
[Codespeed] Misleading order of Python versions

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/performance#23]
Bars on hystograms on https://speed.python.org/comparison/ are ordered in strange order: 2.7-3.6-3.5-master. Legends are ordered in inversed order: master-3.5-3.6-2.7. Both are misleading.

It would be better to support the order 2.7-3.5-3.6-master in both cases.

**Comment by haypo** [comment]
https://speed.python.org/comparison/ comes from:
https://github.com/tobami/codespeed/

It seems like the list of Executables comes from:
https://github.com/tobami/codespeed/blob/master/codespeed/views_data.py#L109
