### ISSUE TITLE
parse_cpu_list() causes the benchmark to fail

### ISSUE THREAD

**Issue by zhangyangyu** [python/performance#29]
When using `performance` in my environment, it fails immediately due to an error:

> Traceback (most recent call last):
>   File "/tmp/venv/lib/python2.7/site-packages/performance/benchmarks/bm_2to3.py", line 30, in <module>
>     runner.bench_func('2to3', bench_2to3, command, devnull_out)
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_runner.py", line 485, in bench_func
>     return self._main(task)
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_runner.py", line 415, in _main
>     bench = self._worker(task)
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_runner.py", line 389, in _worker
>     run = task.create_run()
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_worker.py", line 293, in create_run
>     self.compute()
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_worker.py", line 318, in compute
>     WorkerTask.compute(self)
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_worker.py", line 285, in compute
>     metadata2 = self.collect_metadata()
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_worker.py", line 350, in collect_metadata
>     return collect_metadata()
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_collect_metadata.py", line 416, in collect_metadata
>     collect_cpu_metadata(metadata)
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_collect_metadata.py", line 405, in collect_cpu_metadata
>     collect_cpu_config(metadata, all_cpus)
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_collect_metadata.py", line 291, in collect_cpu_config
>     nohz_full = parse_cpu_list(nohz_full)
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_cpu_utils.py", line 97, in parse_cpu_list
>     cpus.append(int(part))
> ValueError: invalid literal for int() with base 10: ''

Tracing the problem I find the content of `/sys/devices/system/cpu/nohz_full` is `"\x00\n"`. So `int("\x00")` fails.

**Comment by haypo** [comment]
I just released perf 1.4 which fixes the bug: can you try manually "python3 -m perf collect_metadata" (using perf 1.4) to confirm that the bug is fixed?

I already upgrade perf requirement from 1.3 to 1.4 in performance.

**Comment by haypo** [comment]
If collect_metadata works for you, I will release performance 0.6.0.

**Comment by zhangyangyu** [comment]
Confirmed. 1.3 fails with the ValueError and 1.4 succeeds:

1.3:

>  python -m perf collect_metadata
> Traceback (most recent call last):
>   File "/opt/py2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/opt/py2.7/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/tmp/venv/lib/python2.7/site-packages/perf/__main__.py", line 760, in <module>
>     main()
>   File "/tmp/venv/lib/python2.7/site-packages/perf/__main__.py", line 756, in main
>     func()
>   File "/tmp/venv/lib/python2.7/site-packages/perf/__main__.py", line 404, in cmd_collect_metadata
>     func(args)
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_collect_metadata.py", line 441, in cmd_collect_metadata
>     run = perf.Run([1.0])
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_bench.py", line 121, in __init__
>     metadata2 = collect_func()
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_collect_metadata.py", line 416, in collect_metadata
>     collect_cpu_metadata(metadata)
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_collect_metadata.py", line 405, in collect_cpu_metadata
>     collect_cpu_config(metadata, all_cpus)
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_collect_metadata.py", line 291, in collect_cpu_config
>     nohz_full = parse_cpu_list(nohz_full)
>   File "/tmp/venv/lib/python2.7/site-packages/perf/_cpu_utils.py", line 96, in parse_cpu_list
>     cpus.append(int(part))
> ValueError: invalid literal for int() with base 10: ''

1.4

> Metadata:
> - aslr: Full randomization
> - boot_time: 2017-07-06 20:14:37
> - cpu_config: idle:none
> - cpu_count: 16
> - cpu_freq: 0-15=2394 MHz
> - cpu_model_name: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
> - date: 2017-07-06 20:19:02.244528
> - hostname: SZX1000328166
> - load_avg_1min: 0.41
> - mem_max_rss: 12.0 MB
> - perf_version: 1.4
> - platform: Linux-3.10.0-514.21.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
> - python_cflags: -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
> - python_executable: /opt/py2.7/bin/python
> - python_implementation: cpython
> - python_unicode: UTF-16
> - python_version: 2.7.13+ (64-bit)
> - runnable_threads: 1
> - timer: time.time()
> - uptime: 4 min 25.3 sec

Thanks!

**Comment by haypo** [comment]
Ok, I released performance 0.6.0.
